### ISSUE TITLE
Develop API Specification for plugin

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#1]
- [ ] Gather and document API use cases (plugin usage) (start from #3 #12 #7 #13 #4)
- [ ] Consult with other factcheckers
- [ ] Develop API specification
- [ ] Document it in Swagger

Acceptance criteria:
- swagger documentation for API
- Documentation of use cases

**Comment by KrzysztofMadejski** [comment]
General info on API, CC @yozness, exact API spec will be developed based on use cases

API should expose the data from fact-checking website, particularly:
- all the fact-checked statements
  - text
  - rating
  - justification
  - person (name, id)
  - link to the statement and justification on the fact-checking website
  - link to the source of the statement (news article, youtube video, gov website, etc.)
- all the sources that has been fact-checked
  - url of the source
  - links to statements in API that has been fact-checked in this source

**Comment by KrzysztofMadejski** [comment]
@voidberg has developed a draft documentation: http://docs.factualapi.apiary.io/#

**Comment by KrzysztofMadejski** [comment]
I have added _User Scenarios_  and _API features spec_ for issues/use cases #3 #12 #7 #13

**Summary:**
API feature: For any URL the API should provide a list of Statements that appear in this URL.
API feature: Provide a list of all Sources (URLs).
API feature: Querying for any URL should contain a piece of information identifying the way of accessing the Statements (is it being highlighted by plugin? on partner media for user without a plugin? did user navigated from facebook highlight?).

@voidberg so to your [API draft](http://docs.factualapi.apiary.io/#) I'd add:
- list of websites, ie. `websites/`
- for `/facts?uri=` piece of information identyfiying the way of accessing the data. Could we name it `origin`: `chrome-extension` | `media-partner` ? (see #14)

Also I believe that we should work to create a common dictionary of term.  I've created an issue for that -> #14

In general, how do you @voidberg feel about using http://jsonapi.org/ convention? (http://jsonapi.org/implementations/#server-libraries-php)

**Comment by KrzysztofMadejski** [comment]
I wonder if being json-api compliant is not an overkill.

# With JsonAPI

[With JSON-API](https://github.com/TransparenCEE/factchecker-plugin-chrome/blob/bdb5e5f4d6c0d07574dd49dab3c91f9ac1bf2a23/docs/api-design.apib) we have all the bloat of `relationships`, `included`, etc.

The needed calls in this option are:
- http://factual.ro/sources/http://www.agerpres.ro/politica/2016/07/10/dragnea-de-cand-e-gabriela-firea-primar-nu-s-a-taiat-niciun-pom-pe-kiseleff-21-41-07/statements to get statements on given url (assuming we identify sources by the full url)

```
GET http://factual.ro/sources/http://www.agerpres.ro/politica/2016/07/10/dragnea-de-cand-e-gabriela-firea-primar-nu-s-a-taiat-niciun-pom-pe-kiseleff-21-41-07/statements
{
  "data": {
    "id": "1",
    "type": "source",
    "attributes": {
      "uri": "http://www.agerpres.ro/politica/2016/07/10/dragnea"
    },
    "relationships": {
      "statements": {
        "links": {
          "self": "http://factual.ro/api/sources/1/relationships/statements",
          "related": "http://factual.ro/api/sources/1/statements"
        },
        "data": {
          "type": "statement",
          "id": "1"
        }
      }
    }
  },
  "included": [
    {
      "id": "1",
      "type": "statement",
      "attributes": {
        "text": "We in Indiana have . . . the highest credit rating in the nation.",
        "person_name": "Mike Pence",
        "rating": "false",
        "explanation": "Indiana Gov. Mike Pence, the Republican nominee for vice president, introduced himself...",
        "factchecker_uri": "http://www.politifact.com/truth",
        "sources": "http://www.agerpres.ro/politica/2016/07/10/dragnea"
      }
    }
  ]
}
```
- http://factual.ro/sources - to get the full list of URLs (though the answer would be quite bloated)

```
GET http://factual.ro/sources
{
  "data": [
    {
      "id": "1",
      "type": "source",
      "attributes": {
        "uri": "http://www.agerpres.ro/politica/2016/07/10/dragnea"
      },
      "relationships": {
        "statements": {
          "links": {
            "self": "http://factual.ro/api/sources/1/relationships/statements",
            "related": "http://factual.ro/api/sources/1/statements"
          },
          "data": {
            "type": "statement",
            "id": "1"
          }
        }
      }
    }
  ],
  "links": {
    "first": "http://factual.ro/api/sources?page[number]=0",
    "last": "http://factual.ro/api/sources?page[number]=3",
    "prev": "http://factual.ro/api/sources?page[offset]=0",
    "next": "http://factual.ro/api/sources?page[offset]=2"
  }
}
```

What comes to mind: /statements is not used at all.

# [Without JsonAPI](https://github.com/TransparenCEE/factchecker-plugin-chrome/blob/c0aae692fef3d43f2567ca325761cc670dcbec56/docs/api-design.apib) (or limited)

Then the calls are:
- http://factual.ro/api/statements?uri=http://www.agerpres.ro/politica/2016/07/10/dragnea to get statements on given url

```
   [
    {
      "id": "1",
      "type": "statement",
      "attributes": {
        "text": "We in Indiana have . . . the highest credit rating in the nation.",
        "person_name": "Mike Pence",
        "rating": "false",
        "explanation": "Indiana Gov. Mike Pence, the Republican nominee for vice president, introduced himself...",
        "factchecker_uri": "http://www.politifact.com/truth",
        "sources": "http://www.agerpres.ro/politica/2016/07/10/dragnea"
      }
    }
  ]
```
- http://factual.ro/api/sources - to get the full list of URLs 
  No JsonAPI at all:

```
    ["http://www.agerpres.ro/politica/2016/07/10/dragnea", ...]
```

or limited jsonAPI (without relationships)

```
    {
   "data": [
    {
      "id": "1",
      "type": "source",
      "attributes": {
        "uri": "http://www.agerpres.ro/politica/2016/07/10/dragnea"
      },
    ] }
```

# Conclusion

If we drop the paging, then we can go super minimal.

If we need paging I'd go with limited jsonAPI - have the separation of `links` and `data` and dropping the `relationships` part. 

If we are thinking about proper REST for the future (associating statements with URLs, allowing to query the statements for other solutions, separating people) then we could go full-blown jsonAPI. Though now I think it can be quite hard to implement on the backend (a separate DB would be needed to store unique urls, etc. or a really hardcore custom implemntation for json API).

@voidberg what do you think? @yozness should we ask Catalin for a comment? I'd go for paging one.

**Comment by voidberg** [comment]
Agree, it seems overkill. I'm all for HATEOAS and things like that if it makes sense but in our case I don't think it does, the things we actually need are pretty small and we wouldn't really be using the links and relationships.

**Comment by KrzysztofMadejski** [comment]
The latest version is available at http://docs.factualkm.apiary.io/#

**Comment by KrzysztofMadejski** [comment]
- [ ] Update the specification to reflect the API

**Comment by catalintenita** [comment]
@KrzysztofMadejski
Here is the updated schema.
It's in the documentation (README.txt file).
Let me know if you want it some other files/online docs as well

---

API request method example:
http://www.factual.ro/api/?q=a5605c929a9611efaaa5ba66bbafc7bf

"q" variable is a md5  hash code of the assigned link.

Note: In order to insure the privacy of the Chrome extension user, the communication of the URL between the factual.ro server and the client (the Chrome extension) used the MD5 method to hash the content of the URL. Otherwise the factual.ro admin might know all the browsing history of a particular user.

Data output/response schema (JSON formated):

q  = the URL hash code
declaratie = the declaration that was validated/invalidated by the fact-checking team
context = the context where the declaration was issued 
status = the status of the declaration (false, true, partially true)
concluzie = the conclusion of the fact-checking team
sursa = the source of the declaration
URL =  the online resource of the fact-checking iteam 

JSON response schema: 

{
  "type": "object",
  "properties": {
    "q": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {
        "147": {
          "type": "object",
          "properties": {
            "declaratie": {
              "type": "string"
            },
            "context": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "concluzie": {
              "type": "string"
            },
            "sursa": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "date": {
              "type": "integer"
            }
          },
          "required": [
            "declaratie",
            "context",
            "status",
            "concluzie",
            "sursa",
            "url",
            "date"
          ]
        }
      },
      "required": [
        "147"
      ]
    }
  },
  "required": [
    "q",
    "data"
  ]
}

Response example:
{
"q":"a5605c929a9611efaaa5ba66bbafc7bf",
"data":{
"147":{
"declaratie":"Gabi Firea este sprijinit\u0103 de partid, a fost sprijinit\u0103 s\u0103 c\u00e2\u0219tige alegerile, este \u0219i acum. Am v\u0103zut o \u0219tire c\u0103 Gabi Firea a t\u0103iat pomii pe Kiseleff. Nu exist\u0103 a\u0219a ceva. Nu s-a t\u0103iat niciun pom.",
"context":"<span style=\"font-weight: 400;\">Invitat \u00een cadrul unei emisiuni de la Rom\u00e2nia Tv, pre\u0219edintele PSD, Liviu Dragnea, <\/span><a href=\"http:\/\/www.agerpres.ro\/politica\/2016\/07\/10\/dragnea-de-cand-e-gabriela-firea-primar-nu-s-a-taiat-niciun-pom-pe-kiseleff-21-41-07\"><span style=\"font-weight: 400;\">a declarat<\/span><\/a><span style=\"font-weight: 400;\">:<\/span>\r\n\r\n \r\n<blockquote>Gabi Firea este sprijinit\u0103 de partid, a fost sprijinit\u0103 s\u0103 c\u00e2\u0219tige alegerile, este \u0219i acum. Am v\u0103zut o \u0219tire c\u0103 Gabi Firea a t\u0103iat pomii pe Kiseleff. Nu exist\u0103 a\u0219a ceva. Nu s-a t\u0103iat niciun pom. Vreau s\u0103 v\u0103 spun ceva, e foarte simplu, dac\u0103 pe Kiseleff s-ar t\u0103ia o crengu\u021b\u0103 toate televiziunile ar fi acolo, c\u0103 e Kiseleff. Alea erau poze de nu \u0219tiu c\u00e2nd. Nu avea cum ca s\u0103 se taie un pom pe Kiseleff, ca s\u0103 se taie un pom trebuie s\u0103 fie blocat Kiselefful. De c\u00e2nd e Gabi Firea primar nu s-a t\u0103iat niciun pom.<\/blockquote>",
"status":"Fals",
"concluzie":"<span style=\"font-weight: 400;\"><strong>Declara\u021bia lui Liviu Dragnea este fals\u0103<\/strong>. La 6 zile de c\u00e2nd Gabriela Firea a preluat func\u021bia de primar general al capitalei, Direc\u021bia de Mediu din cadrul PMB a emis aviz pentru defri\u0219area a 72 de arbori de c\u0103tre ADP Sector 1, inclusiv pe Bd. Kiseleff.<\/span>",
"sursa":"",
"url":"http:\/\/www.factual.ro\/declaratii\/liviu-dragnea-de-cand-e-gabi-firea-primar-nu-s-taiat-niciun-pom\/",
"date":1468303937
}
}
}
http://www.factual.ro/api/?q=all - "q=all" method return all the factchecks from the databases.

**Comment by KrzysztofMadejski** [comment]
OK, thx!

For new projects it will have to be updated as it's in Romanian, so I'm not touching the blueprint specification.

@voidberg - what URL param do you use to send user token?

About http://www.factual.ro/api/?q=all: it returns all factchecks. Is it needed? I've thought we're caching only urls, not the whole content
