### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#22]
## How to monitor usage of the plugin (#13) and make it operate in a privacy-friendly way?

_Problem_: sending all the browsing history to server, while asking is there anything fact-checked there.

Solution 1: Cache the list of checked URLs in local browser and ask only for statements if the url is in the list. @voidberg I think this caching will be neccessary for highlighting on Faceebook #7 and homepage of hotnews.

Solution 2: While asking for url hash it usign md5 or sha1. Thanks Catalin for the idea.

_Problem_: how to monitor unique active extension users without identyfying them?

Will downloads from Chrome store be enough? If we're caching the URLs list then querying for that daily will give us number of users.

**Comment by voidberg** [comment]
The localStorage limit for Chrome extensions is 5 megabytes. This can, in theory, give us plenty of space to cache the facts but it doesn't scale. However, we might not reach that scale level any time soon or ever. A problem here, however, is that we can't store objects. Storing a string that we keep deserialising / serialising is not ok imho.

There's also chrome.storage which is nice, can keep objects and syncs between Chrome installations. Local limit is 5 megabytes and sync limit is 100 k. We would probably not sync the list since it will be downloaded once a day.

For analytics we could use something like https://heapanalytics.com which has a generous free tier and monitor users by a unique token that we generate on first install and we sync across installations. A complete wipe of the extension and a reinstallation would see that user as new, however.

**Comment by KrzysztofMadejski** [comment]
We don't need to cache the facts, we just need list of URLs. 5MB should be enough for that for long.
