### ISSUE TITLE
Coding Chrome extension

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#5]
Dependent on #3 and #4

Acceptance criteria:
- doesn't slow browser [tested with opening 15 tabs, 5 of them with highlighted items]
- operates on API #1
- implemented features mentioned in #3 and #4
- doesn't double markup when it is already embedded by partnering media

Possibly to reuse:
- check [the prototype](https://github.com/KrzysztofMadejski/factchecker-plugin-chrome)
- https://github.com/julmot/mark.js (used in the prototype)
- https://hypothes.is/

Questions:
- will it scale?
- there are limits on local storage, how much info we want to store locally

**Comment by KrzysztofMadejski** [comment]
@voidberg are you using finally https://github.com/julmot/mark.js ?

They have even add the functionality for custom highlighting I've proposed: https://github.com/julmot/mark.js/issues/20

**Comment by voidberg** [comment]
Haven't decided on what exactly to use, will take a look at `mark.js`.

Thanks!

**Comment by KrzysztofMadejski** [comment]
@voidberg: is it possible to add some unique identifiers to installed extensions so we know how many people are using it actively? It would be beneficial for assessing impact #20. I'm wondering also, what about #privacyissues - tracking what articles ppl view..

**Comment by voidberg** [comment]
Yes, see my answer at #22

**Comment by KrzysztofMadejski** [comment]
I think that the popup (in case of popup visualization) should be shown on hover. Now it's on click. Why did you decided on that?

**Comment by yozness** [comment]
We thought it would be less intrusive in this way, but still attract attention due to the color highlighting in the background of the next (which entices curious users to click and discover what it is about). We don't want to shove our content in their faces, not to be very spammy. I think it is fair enough to let the users have the power to click or not (I mean the decision should be up to them).

**Comment by KrzysztofMadejski** [comment]
Ok. But then I'm advocating for asking users feedback in the promotion campaign, like "Try our new plugin and let us know how we can improve it". So in case it's not seen we will know that. What do you think?

**Comment by voidberg** [comment]
The reason I added it on click was because the popup is not a simple tooltip but rather something that the user can interact with: go to the fact url on factual and share. On / off on hover means it's very easy for the user to dismiss it by accident by moving around the mouse.

We had two alternatives for this but I am not sure if anything was decided:
- Those 3 dots I used, turn them into the factual logo or something similar.
- Show a small tooltip on hover, something like "Click to see if it's true", and also add a close button on the main popup.
